# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

def pods
 pod 'SwiftLint'
 pod 'SnapKit'
 pod 'Then'
 pod 'lottie-ios'
 pod 'FSCalendar'
 pod 'PanModal'
 pod 'PagingKit'
 pod 'YPImagePicker'
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'NSObject+Rx'
 pod 'RxKeyboard'
 pod 'RxDataSources'
 pod 'ReactorKit'
 pod 'naveridlogin-sdk-ios'
 pod 'KakaoSDKCommon'
 pod 'KakaoSDKAuth'
 pod 'KakaoSDKUser'
end

target 'Cookid' do

  pods
  target 'CookidTests' do
     inherit! :search_paths
  end
end
