# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def pods
 pod 'SwiftLint'
 pod 'SnapKit'
 pod 'Then'
 pod 'lottie-ios'
 pod 'Kingfisher', '~> 6.0'
 pod 'FSCalendar'
 pod 'PanModal'
 pod 'PagingKit'
 pod 'YPImagePicker'
 pod 'RxSwift'
 pod 'RxCocoa'
 pod 'NSObject+Rx'
 pod 'RxKeyboard'
 pod 'RxDataSources'
 pod 'ReactorKit'
 pod 'naveridlogin-sdk-ios'
 pod 'KakaoSDKCommon'
 pod 'KakaoSDKAuth'
 pod 'KakaoSDKUser'
end

target 'Cookid' do
  use_frameworks!
  pods
end
