# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cookid' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cookid
pod 'RxSwift'
pod 'RxCocoa'
pod 'NSObject+Rx'
pod 'Action'
pod 'RxKeyboard'
pod 'RxDataSources'
pod 'MBCircularProgressBar'
pod 'PanModal'
pod 'Kingfisher', '~> 6.0'
pod 'lottie-ios'
pod 'FSCalendar'
pod 'Then'
pod 'SnapKit', '~> 5.0.0'
end
