# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new release build to the App Store"
  lane :release do
    cocoapods(use_bundle_exec: false)
    increment_build_number(xcodeproj: "Cookid.xcodeproj")
    build_app(workspace: "Cookid.xcworkspace", scheme: "Cookid")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
    slack(
    message: "Testflight 배포에 성공했습니다!",
    slack_url: "https://hooks.slack.com/services/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"
    )
  end

  desc "build app and upload to TestFlight"
  lane :beta do
    cocoapods(use_bundle_exec: false)
    increment_build_number(xcodeproj: "Cookid.xcodeproj")
    build_app(
	 configuration: "Release"
    )
    upload_to_testflight(
	 skip_waiting_for_build_processing: true
    )
    slack(
    message: "Testflight 배포에 성공했습니다!",
    slack_url: "https://hooks.slack.com/services/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"
    )
  end

  error do |lane, exception, options|
    slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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",
    )
  end
end
