# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "build app and upload to TestFlight"
  lane :beta do
    get_certificates
    get_provisioning_profile
    cocoapods(use_bundle_exec: false)

    increment_build_number(
        build_number: latest_testflight_build_number + 1
    )
    build_app(
	configuration: "Debug"
    )
    upload_to_testflight(
	skip_waiting_for_build_processing: true
    )
    slack(
    message: "Testflight 배포에 성공했습니다!",
    slack_url: "https://hooks.slack.com/services/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"
    )
  end

  desc "build app and release to App Store."
  lane :release do |options|
    if options[:v]
      get_certificates
      get_provisioning_profile
      cocoapods(use_bundle_exec: false)
      build_app(
        configuration: "Release"
      )
      upload_to_app_store(
        app_version: options[:v],
        submit_for_review: true,
        force: true,
        automatic_release: true,
        skip_screenshots: false,
        screenshots_path: "./screenshots",
        overwrite_screenshots: true,
        skip_metadata: false,
        metadata_path: "./metadata",
        skip_app_version_update: false
     )
     slack(
        message: "Appstore 배포에 성공했습니다!",
        slack_url: "https://hooks.slack.com/services/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"
     )
    end
  end

  error do |lane, exception, options|
    slack(
      message: "에러 발생 : #{exception}",
      success: false,
      slack_url: "https://hooks.slack.com/services/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",
    )
  end

end
